# Generated by Django 5.2.16 on 2026-07-23 01:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rebanho", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdutoSaude",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=160, verbose_name="nome")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("VACINA", "Vacina"),
                            ("VERMIFUGO", "Vermífugo"),
                            ("MEDICAMENTO", "Medicamento"),
                            ("TRATAMENTO", "Tratamento"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=16,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "fabricante",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="fabricante"
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        default="mL", max_length=30, verbose_name="unidade"
                    ),
                ),
                (
                    "carencia_padrao_dias",
                    models.PositiveIntegerField(
                        default=0, verbose_name="carência padrão (dias)"
                    ),
                ),
                (
                    "carencia_padrao_horas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="carência padrão (horas)"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "produto de saúde",
                "verbose_name_plural": "produtos de saúde",
                "ordering": ("nome", "fabricante"),
                "indexes": [
                    models.Index(
                        fields=["tipo", "ativo"], name="saude_prod_tipo_ativo_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("nome", "fabricante"),
                        name="saude_produto_nome_fabricante_unico",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Tratamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo_registro", models.BooleanField(db_index=True, default=True)),
                ("cancelado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "data_hora",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="data e hora"
                    ),
                ),
                (
                    "dose",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="dose",
                    ),
                ),
                ("unidade", models.CharField(max_length=30, verbose_name="unidade")),
                (
                    "responsavel",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="responsável"
                    ),
                ),
                ("motivo", models.TextField(verbose_name="motivo")),
                (
                    "carencia_dias",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Confirme a carência conforme a bula e a orientação do médico-veterinário.",
                        verbose_name="carência (dias)",
                    ),
                ),
                (
                    "carencia_horas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="carência adicional (horas)"
                    ),
                ),
                (
                    "data_liberacao",
                    models.DateTimeField(
                        editable=False, verbose_name="data de liberação"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("REGISTRADO", "Registrado"),
                            ("CORRIGIDO", "Corrigido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="REGISTRADO",
                        max_length=12,
                        verbose_name="situação",
                    ),
                ),
                (
                    "motivo_correcao",
                    models.TextField(blank=True, verbose_name="motivo da correção"),
                ),
                (
                    "motivo_cancelamento",
                    models.TextField(blank=True, verbose_name="motivo do cancelamento"),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tratamentos",
                        to="rebanho.animal",
                        verbose_name="animal",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tratamentos",
                        to="saude.produtosaude",
                        verbose_name="produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "tratamento",
                "verbose_name_plural": "tratamentos",
                "ordering": ("-data_hora", "animal"),
                "indexes": [
                    models.Index(
                        fields=["animal", "data_liberacao"],
                        name="saude_trat_animal_lib_idx",
                    ),
                    models.Index(
                        fields=["situacao", "data_hora"], name="saude_trat_sit_data_idx"
                    ),
                    models.Index(
                        fields=["data_liberacao"], name="saude_trat_liberacao_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("dose__gt", 0)),
                        name="saude_tratamento_dose_positiva",
                    )
                ],
            },
        ),
    ]
