# Generated by Django 5.2.16 on 2026-07-23 02:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rebanho", "0002_alter_animal_foto"),
        ("saude", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoSaude",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo_registro", models.BooleanField(db_index=True, default=True)),
                ("cancelado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DOENCA", "Doença"),
                            ("PROCEDIMENTO", "Procedimento"),
                            ("EXAME", "Exame"),
                            ("OBSERVACAO_VETERINARIA", "Observação veterinária"),
                        ],
                        max_length=24,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="data e hora efetiva",
                    ),
                ),
                ("titulo", models.CharField(max_length=180, verbose_name="título")),
                ("descricao", models.TextField(verbose_name="descrição")),
                (
                    "veterinario",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="médico-veterinário"
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="outro responsável"
                    ),
                ),
                (
                    "resultado",
                    models.TextField(blank=True, verbose_name="resultado/conclusão"),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("REGISTRADO", "Registrado"),
                            ("CORRIGIDO", "Corrigido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="REGISTRADO",
                        max_length=12,
                        verbose_name="situação",
                    ),
                ),
                (
                    "motivo_correcao",
                    models.TextField(
                        blank=True, verbose_name="justificativa da correção"
                    ),
                ),
                (
                    "motivo_cancelamento",
                    models.TextField(
                        blank=True, verbose_name="justificativa do cancelamento"
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eventos_saude",
                        to="rebanho.animal",
                        verbose_name="animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "evento de saúde",
                "verbose_name_plural": "eventos de saúde",
                "ordering": ("-data_hora", "animal", "titulo"),
                "indexes": [
                    models.Index(
                        fields=["animal", "data_hora"],
                        name="saude_evento_animal_data_idx",
                    ),
                    models.Index(
                        fields=["tipo", "data_hora"], name="saude_evento_tipo_data_idx"
                    ),
                    models.Index(
                        fields=["situacao", "data_hora"],
                        name="saude_evento_sit_data_idx",
                    ),
                ],
            },
        ),
    ]
