# Generated by Django 5.2.16 on 2026-07-23 01:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoSistema",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "nome_propriedade",
                    models.CharField(default="Minha propriedade", max_length=120),
                ),
                ("gestacao_dias", models.PositiveSmallIntegerField(default=283)),
                ("margem_parto_dias", models.PositiveSmallIntegerField(default=7)),
                ("dias_diagnostico", models.PositiveSmallIntegerField(default=45)),
                ("dias_secagem", models.PositiveSmallIntegerField(default=60)),
                ("idade_bezerro_meses", models.PositiveSmallIntegerField(default=12)),
                ("idade_novilha_meses", models.PositiveSmallIntegerField(default=15)),
                (
                    "queda_producao_percentual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "tolerancia_divergencia_litros",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.500"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "tolerancia_divergencia_percentual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "tolerancia_financeira",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("casas_decimais_litros", models.PositiveSmallIntegerField(default=3)),
                ("casas_decimais_peso", models.PositiveSmallIntegerField(default=3)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "configuração do sistema",
                "verbose_name_plural": "configuração do sistema",
            },
        ),
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("tipo", models.CharField(db_index=True, max_length=60)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("info", "Informativo"),
                            ("atencao", "Atenção"),
                            ("urgente", "Urgente"),
                        ],
                        default="atencao",
                        max_length=12,
                    ),
                ),
                ("titulo", models.CharField(max_length=160)),
                ("mensagem", models.TextField()),
                ("entidade", models.CharField(blank=True, max_length=100)),
                ("identificador", models.CharField(blank=True, max_length=64)),
                (
                    "data_referencia",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("resolvido", models.BooleanField(db_index=True, default=False)),
                ("resolvido_em", models.DateTimeField(blank=True, null=True)),
                ("chave", models.CharField(max_length=190, unique=True)),
                (
                    "resolvido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas_resolvidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["resolvido", "data_referencia", "-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["tipo", "resolvido"], name="core_alerta_tipo_42a8ed_idx"
                    )
                ],
            },
        ),
    ]
