# Generated by Django 5.2.16 on 2026-07-23 02:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArquivoAnexo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("object_id", models.CharField(db_index=True, max_length=64)),
                ("campo", models.CharField(max_length=80)),
                ("caminho", models.CharField(max_length=500)),
                ("nome_original", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=120)),
                ("tamanho_bytes", models.PositiveBigIntegerField()),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                ("substituido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arquivos_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "metadado de arquivo privado",
                "verbose_name_plural": "metadados de arquivos privados",
                "ordering": ("-enviado_em",),
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "campo", "ativo"],
                        name="core_arquivo_obj_campo_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ativo", True)),
                        fields=("content_type", "object_id", "campo"),
                        name="core_arquivo_ativo_obj_campo_unico",
                    )
                ],
            },
        ),
    ]
