# Generated by Django 5.2.16 on 2026-07-27 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_configuracaosistema_alertas_leite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configuracaosistema",
            name="antecedencia_alerta_secagem_dias",
        ),
        migrations.RemoveField(
            model_name="configuracaosistema",
            name="casas_decimais_litros",
        ),
        migrations.RemoveField(
            model_name="configuracaosistema",
            name="casas_decimais_peso",
        ),
        migrations.RemoveField(
            model_name="configuracaosistema",
            name="dias_secagem",
        ),
        migrations.RemoveField(
            model_name="configuracaosistema",
            name="dias_sem_ordenha_alerta",
        ),
        migrations.RemoveField(
            model_name="configuracaosistema",
            name="idade_novilha_meses",
        ),
        migrations.RemoveField(
            model_name="configuracaosistema",
            name="queda_producao_percentual",
        ),
        migrations.RemoveField(
            model_name="configuracaosistema",
            name="tolerancia_financeira",
        ),
        migrations.DeleteModel(
            name="Alerta",
        ),
    ]
