# Generated by Django 5.2.16 on 2026-07-23 01:00

import apps.financeiro.models
import apps.financeiro.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EntregaLeite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo_registro", models.BooleanField(db_index=True, default=True)),
                ("cancelado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "data_coleta",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="data e hora da coleta",
                    ),
                ),
                (
                    "quantidade_litros",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="quantidade (L)",
                    ),
                ),
                (
                    "valor_litro",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="valor por litro",
                    ),
                ),
                (
                    "preco_manual",
                    models.BooleanField(
                        default=False, verbose_name="preço informado manualmente"
                    ),
                ),
                (
                    "justificativa_preco",
                    models.TextField(
                        blank=True, verbose_name="justificativa do preço manual"
                    ),
                ),
                (
                    "valor_bruto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=14,
                        verbose_name="valor bruto",
                    ),
                ),
                (
                    "bonificacao_qualidade",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="bonificação por qualidade",
                    ),
                ),
                (
                    "bonificacao_volume",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="bonificação por volume",
                    ),
                ),
                (
                    "outras_bonificacoes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="outras bonificações",
                    ),
                ),
                (
                    "desconto_qualidade",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="desconto por qualidade",
                    ),
                ),
                (
                    "frete",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="frete",
                    ),
                ),
                (
                    "taxas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="taxas",
                    ),
                ),
                (
                    "outros_descontos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="outros descontos",
                    ),
                ),
                (
                    "total_bonificacoes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=14,
                        verbose_name="total de bonificações",
                    ),
                ),
                (
                    "total_descontos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=14,
                        verbose_name="total de descontos",
                    ),
                ),
                (
                    "valor_liquido",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=14,
                        verbose_name="valor líquido",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("REGISTRADA", "Registrada"),
                            ("AGUARDANDO_FECHAMENTO", "Aguardando fechamento"),
                            ("FECHADA", "Fechada"),
                            ("PARCIALMENTE_PAGA", "Parcialmente paga"),
                            ("PAGA", "Paga"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="AGUARDANDO_FECHAMENTO",
                        max_length=24,
                        verbose_name="situação",
                    ),
                ),
                (
                    "data_prevista_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="data prevista de pagamento"
                    ),
                ),
                (
                    "data_pagamento_integral",
                    models.DateField(
                        blank=True, null=True, verbose_name="data do pagamento integral"
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nota ou romaneio"
                    ),
                ),
                (
                    "anexo",
                    models.FileField(
                        blank=True,
                        upload_to=apps.financeiro.models.caminho_anexo_entrega,
                        validators=[apps.financeiro.validators.validar_anexo],
                        verbose_name="anexo",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "motivo_correcao",
                    models.TextField(blank=True, verbose_name="motivo da correção"),
                ),
                (
                    "motivo_cancelamento",
                    models.TextField(blank=True, verbose_name="motivo do cancelamento"),
                ),
            ],
            options={
                "verbose_name": "entrega de leite",
                "verbose_name_plural": "entregas de leite",
                "ordering": ("-data_coleta", "-criado_em"),
            },
        ),
        migrations.CreateModel(
            name="Laticinio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "razao_social",
                    models.CharField(max_length=200, verbose_name="razão social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="nome fantasia"
                    ),
                ),
                (
                    "cpf_cnpj",
                    models.CharField(
                        blank=True,
                        max_length=18,
                        validators=[apps.financeiro.validators.validar_cpf_cnpj],
                        verbose_name="CNPJ ou CPF",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                ("endereco", models.TextField(blank=True, verbose_name="endereço")),
                (
                    "codigo_produtor",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="código do produtor"
                    ),
                ),
                (
                    "dia_fechamento",
                    models.PositiveSmallIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="dia habitual de fechamento",
                    ),
                ),
                (
                    "dia_pagamento",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="dia habitual de pagamento",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "laticínio",
                "verbose_name_plural": "laticínios",
                "ordering": ("-ativo", "razao_social"),
                "indexes": [
                    models.Index(fields=["ativo"], name="financeiro_lat_ativo_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ativo", True)),
                        fields=("ativo",),
                        name="financeiro_apenas_um_laticinio_ativo",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FechamentoLeite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo_registro", models.BooleanField(db_index=True, default=True)),
                ("cancelado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "competencia",
                    models.DateField(
                        help_text="Use o primeiro dia do mês.",
                        verbose_name="competência",
                    ),
                ),
                ("data_inicial", models.DateField(verbose_name="data inicial")),
                ("data_final", models.DateField(verbose_name="data final")),
                (
                    "total_litros_calculado",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        editable=False,
                        max_digits=14,
                        verbose_name="litros calculados",
                    ),
                ),
                (
                    "valor_bruto_calculado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=14,
                        verbose_name="valor bruto calculado",
                    ),
                ),
                (
                    "bonificacoes_calculadas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=14,
                        verbose_name="bonificações calculadas",
                    ),
                ),
                (
                    "descontos_calculados",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=14,
                        verbose_name="descontos calculados",
                    ),
                ),
                (
                    "valor_liquido_calculado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=14,
                        verbose_name="valor líquido calculado",
                    ),
                ),
                (
                    "total_litros_informado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="litros informados",
                    ),
                ),
                (
                    "valor_bruto_informado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="valor bruto informado",
                    ),
                ),
                (
                    "bonificacoes_informadas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="bonificações informadas",
                    ),
                ),
                (
                    "descontos_informados",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="descontos informados",
                    ),
                ),
                (
                    "valor_liquido_informado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="valor líquido informado",
                    ),
                ),
                (
                    "data_prevista_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="data prevista de pagamento"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("ABERTO", "Em aberto"),
                            ("FECHADO", "Fechado"),
                            ("PARCIALMENTE_PAGO", "Parcialmente pago"),
                            ("PAGO", "Pago"),
                            ("DIVERGENTE", "Divergente"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="ABERTO",
                        max_length=20,
                        verbose_name="situação",
                    ),
                ),
                (
                    "numero_demonstrativo",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="número do demonstrativo",
                    ),
                ),
                (
                    "arquivo_demonstrativo",
                    models.FileField(
                        blank=True,
                        upload_to=apps.financeiro.models.caminho_demonstrativo,
                        validators=[apps.financeiro.validators.validar_anexo],
                        verbose_name="arquivo do demonstrativo",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "motivo_ajuste",
                    models.TextField(blank=True, verbose_name="motivo do ajuste"),
                ),
                (
                    "motivo_cancelamento",
                    models.TextField(blank=True, verbose_name="motivo do cancelamento"),
                ),
                (
                    "entregas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="fechamentos",
                        to="financeiro.entregaleite",
                        verbose_name="entregas",
                    ),
                ),
                (
                    "laticinio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fechamentos",
                        to="financeiro.laticinio",
                        verbose_name="laticínio",
                    ),
                ),
            ],
            options={
                "verbose_name": "fechamento de leite",
                "verbose_name_plural": "fechamentos de leite",
                "ordering": ("-competencia", "-criado_em"),
            },
        ),
        migrations.AddField(
            model_name="entregaleite",
            name="laticinio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entregas",
                to="financeiro.laticinio",
                verbose_name="laticínio",
            ),
        ),
        migrations.CreateModel(
            name="PrecoLeite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("data_inicial", models.DateField(verbose_name="data inicial")),
                (
                    "data_final",
                    models.DateField(blank=True, null=True, verbose_name="data final"),
                ),
                (
                    "valor_litro",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="valor por litro",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "motivo_alteracao",
                    models.TextField(blank=True, verbose_name="motivo da alteração"),
                ),
                (
                    "laticinio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="precos",
                        to="financeiro.laticinio",
                        verbose_name="laticínio",
                    ),
                ),
            ],
            options={
                "verbose_name": "preço do leite",
                "verbose_name_plural": "histórico de preços do leite",
                "ordering": ("-data_inicial", "-criado_em"),
            },
        ),
        migrations.CreateModel(
            name="RecebimentoLeite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo_registro", models.BooleanField(db_index=True, default=True)),
                ("cancelado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="data"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="valor",
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("TRANSFERENCIA", "Transferência"),
                            ("PIX", "PIX"),
                            ("DINHEIRO", "Dinheiro"),
                            ("CHEQUE", "Cheque"),
                            ("DEPOSITO", "Depósito"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="forma de pagamento",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="referência"
                    ),
                ),
                (
                    "anexo",
                    models.FileField(
                        blank=True,
                        upload_to=apps.financeiro.models.caminho_anexo_recebimento,
                        validators=[apps.financeiro.validators.validar_anexo],
                        verbose_name="anexo",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("CONFIRMADO", "Confirmado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="CONFIRMADO",
                        max_length=12,
                        verbose_name="situação",
                    ),
                ),
                (
                    "justificativa_excesso",
                    models.TextField(
                        blank=True,
                        verbose_name="justificativa para pagamento excedente",
                    ),
                ),
                (
                    "motivo_cancelamento",
                    models.TextField(blank=True, verbose_name="motivo do cancelamento"),
                ),
                (
                    "fechamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recebimentos",
                        to="financeiro.fechamentoleite",
                        verbose_name="fechamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "recebimento de leite",
                "verbose_name_plural": "recebimentos de leite",
                "ordering": ("-data", "-criado_em"),
            },
        ),
        migrations.AddIndex(
            model_name="fechamentoleite",
            index=models.Index(
                fields=["laticinio", "competencia"], name="fin_fech_lat_comp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fechamentoleite",
            index=models.Index(
                fields=["situacao", "data_prevista_pagamento"],
                name="fin_fech_sit_pag_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fechamentoleite",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_final__gte", models.F("data_inicial"))),
                name="financeiro_fechamento_periodo_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="fechamentoleite",
            constraint=models.UniqueConstraint(
                condition=models.Q(("situacao", "CANCELADO"), _negated=True),
                fields=("laticinio", "competencia"),
                name="financeiro_fechamento_competencia_unica",
            ),
        ),
        migrations.AddIndex(
            model_name="entregaleite",
            index=models.Index(
                fields=["laticinio", "data_coleta"], name="fin_entrega_lat_data_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entregaleite",
            index=models.Index(
                fields=["situacao", "data_coleta"], name="fin_entrega_sit_data_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entregaleite",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantidade_litros__gt", 0)),
                name="financeiro_entrega_quantidade_positiva",
            ),
        ),
        migrations.AddConstraint(
            model_name="entregaleite",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor_litro__gte", 0)),
                name="financeiro_entrega_preco_nao_negativo",
            ),
        ),
        migrations.AddIndex(
            model_name="precoleite",
            index=models.Index(
                fields=["laticinio", "data_inicial", "data_final"],
                name="fin_preco_vigencia_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="precoleite",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor_litro__gte", 0)),
                name="financeiro_preco_valor_nao_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="precoleite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("data_final__isnull", True),
                    ("data_final__gte", models.F("data_inicial")),
                    _connector="OR",
                ),
                name="financeiro_preco_periodo_valido",
            ),
        ),
        migrations.AddIndex(
            model_name="recebimentoleite",
            index=models.Index(
                fields=["fechamento", "situacao"], name="fin_receb_fech_sit_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recebimentoleite",
            index=models.Index(fields=["data"], name="fin_receb_data_idx"),
        ),
        migrations.AddConstraint(
            model_name="recebimentoleite",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor__gt", 0)),
                name="financeiro_recebimento_valor_positivo",
            ),
        ),
    ]
