# Generated by Django 5.2.16 on 2026-07-23 01:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rebanho", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cobertura",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("data", models.DateField(verbose_name="data")),
                (
                    "data_original",
                    models.DateField(
                        editable=False, null=True, verbose_name="data original"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MONTA_NATURAL", "Monta natural"),
                            ("INSEMINACAO", "Inseminação"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "forma_identificacao",
                    models.CharField(
                        choices=[
                            ("OBSERVADA", "Observada"),
                            ("ESTIMADA", "Estimada"),
                            ("INFORMADA", "Informada"),
                        ],
                        default="OBSERVADA",
                        max_length=20,
                        verbose_name="forma de identificação",
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("REGISTRADA", "Registrada"),
                            ("AGUARDANDO_CONFIRMACAO", "Aguardando confirmação"),
                            ("PRENHEZ_CONFIRMADA", "Prenhez confirmada"),
                            ("NAO_EMPRENHOU", "Não emprenhou"),
                            ("SUBSTITUIDA", "Substituída por nova cobertura"),
                            ("INCERTA", "Situação incerta"),
                            ("PERDA_GESTACIONAL", "Perda gestacional"),
                            ("FINALIZADA_COM_PARTO", "Finalizada com parto"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="REGISTRADA",
                        max_length=30,
                        verbose_name="situação",
                    ),
                ),
                (
                    "previsao_original_parto",
                    models.DateField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="previsão original do parto",
                    ),
                ),
                (
                    "previsao_atual_parto",
                    models.DateField(
                        blank=True, null=True, verbose_name="previsão atual do parto"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "motivo_alteracao",
                    models.TextField(blank=True, verbose_name="motivo da alteração"),
                ),
                (
                    "motivo_cancelamento",
                    models.TextField(blank=True, verbose_name="motivo do cancelamento"),
                ),
                (
                    "touro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coberturas_como_touro",
                        to="rebanho.animal",
                        verbose_name="touro",
                    ),
                ),
                (
                    "vaca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coberturas",
                        to="rebanho.animal",
                        verbose_name="vaca",
                    ),
                ),
            ],
            options={
                "verbose_name": "cobertura",
                "verbose_name_plural": "coberturas",
                "ordering": ("-data", "-criado_em"),
            },
        ),
        migrations.CreateModel(
            name="DiagnosticoGestacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="data"
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("PRENHE", "Prenhe"),
                            ("VAZIA", "Vazia"),
                            ("INCONCLUSIVO", "Inconclusivo"),
                        ],
                        max_length=20,
                        verbose_name="resultado",
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("PALPACAO", "Palpação"),
                            ("ULTRASSOM", "Ultrassom"),
                            ("EXAME_LABORATORIAL", "Exame laboratorial"),
                            ("OBSERVACAO", "Observação"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="método",
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="responsável"
                    ),
                ),
                (
                    "idade_gestacional_estimada_dias",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="idade gestacional estimada (dias)",
                    ),
                ),
                (
                    "nova_previsao_parto",
                    models.DateField(
                        blank=True, null=True, verbose_name="nova previsão do parto"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "cobertura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnosticos",
                        to="reproducao.cobertura",
                    ),
                ),
                (
                    "vaca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diagnosticos_gestacao",
                        to="rebanho.animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "diagnóstico de gestação",
                "verbose_name_plural": "diagnósticos de gestação",
                "ordering": ("-data", "-criado_em"),
            },
        ),
        migrations.CreateModel(
            name="HistoricoCobertura",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("evento", models.CharField(max_length=50, verbose_name="evento")),
                ("situacao_anterior", models.CharField(blank=True, max_length=30)),
                ("situacao_nova", models.CharField(blank=True, max_length=30)),
                ("previsao_anterior", models.DateField(blank=True, null=True)),
                ("previsao_nova", models.DateField(blank=True, null=True)),
                (
                    "justificativa",
                    models.TextField(blank=True, verbose_name="justificativa"),
                ),
                (
                    "cobertura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico",
                        to="reproducao.cobertura",
                    ),
                ),
            ],
            options={
                "verbose_name": "histórico de cobertura",
                "verbose_name_plural": "históricos de cobertura",
                "ordering": ("-criado_em",),
            },
        ),
        migrations.CreateModel(
            name="Parto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "data_hora",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="data e hora"
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("COM_AUXILIO", "Com auxílio"),
                            ("CESAREA", "Cesárea"),
                            ("ABORTO", "Aborto"),
                            ("NATIMORTO", "Natimorto"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="resultado",
                    ),
                ),
                (
                    "quantidade_bezerros",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="quantidade de bezerros"
                    ),
                ),
                (
                    "necessitou_auxilio",
                    models.BooleanField(
                        default=False, verbose_name="necessitou auxílio"
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="responsável"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("REGISTRADO", "Registrado"),
                            ("CORRIGIDO", "Corrigido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="REGISTRADO",
                        max_length=20,
                        verbose_name="situação",
                    ),
                ),
                (
                    "motivo_correcao",
                    models.TextField(blank=True, verbose_name="motivo da correção"),
                ),
                (
                    "motivo_cancelamento",
                    models.TextField(blank=True, verbose_name="motivo do cancelamento"),
                ),
                (
                    "cobertura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partos",
                        to="reproducao.cobertura",
                    ),
                ),
                (
                    "vaca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partos",
                        to="rebanho.animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "parto",
                "verbose_name_plural": "partos",
                "ordering": ("-data_hora", "-criado_em"),
            },
        ),
        migrations.CreateModel(
            name="Nascimento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("VIVO", "Vivo"),
                            ("NATIMORTO", "Natimorto"),
                            ("MORREU_APOS_NASCIMENTO", "Morreu após nascimento"),
                        ],
                        default="VIVO",
                        max_length=30,
                        verbose_name="situação",
                    ),
                ),
                (
                    "peso_ao_nascer_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="peso ao nascer (kg)",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "animal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nascimento",
                        to="rebanho.animal",
                    ),
                ),
                (
                    "parto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nascimentos",
                        to="reproducao.parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "nascimento",
                "verbose_name_plural": "nascimentos",
                "ordering": ("parto", "criado_em"),
            },
        ),
        migrations.CreateModel(
            name="HistoricoParto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("evento", models.CharField(max_length=30, verbose_name="evento")),
                ("dados_anteriores", models.JSONField(blank=True, default=dict)),
                ("dados_novos", models.JSONField(blank=True, default=dict)),
                ("justificativa", models.TextField(verbose_name="justificativa")),
                (
                    "parto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico",
                        to="reproducao.parto",
                    ),
                ),
            ],
            options={
                "verbose_name": "histórico de parto",
                "verbose_name_plural": "históricos de parto",
                "ordering": ("-criado_em",),
            },
        ),
        migrations.CreateModel(
            name="PerdaGestacional",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="data"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ABORTO", "Aborto"),
                            ("PERDA_GESTACIONAL", "Perda gestacional"),
                            ("REABSORCAO", "Reabsorção"),
                            ("SUSPEITA", "Suspeita"),
                        ],
                        max_length=30,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="responsável"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "cobertura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="perdas_gestacionais",
                        to="reproducao.cobertura",
                    ),
                ),
                (
                    "vaca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="perdas_gestacionais",
                        to="rebanho.animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "perda gestacional",
                "verbose_name_plural": "perdas gestacionais",
                "ordering": ("-data", "-criado_em"),
            },
        ),
        migrations.AddIndex(
            model_name="cobertura",
            index=models.Index(
                fields=["vaca", "situacao", "-data"], name="repro_cob_vaca_sit_data_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cobertura",
            index=models.Index(
                fields=["previsao_atual_parto", "situacao"],
                name="repro_cob_prev_sit_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosticogestacao",
            index=models.Index(
                fields=["cobertura", "-data"], name="repro_diag_cob_data_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosticogestacao",
            index=models.Index(
                fields=["vaca", "resultado", "-data"], name="repro_diag_vaca_res_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historicocobertura",
            index=models.Index(
                fields=["cobertura", "-criado_em"], name="repro_hist_cob_data_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parto",
            index=models.Index(
                fields=["vaca", "-data_hora"], name="repro_parto_vaca_data_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parto",
            index=models.Index(
                fields=["situacao", "-data_hora"], name="repro_parto_sit_data_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="parto",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("cobertura__isnull", False),
                    models.Q(("situacao", "CANCELADO"), _negated=True),
                ),
                fields=("cobertura",),
                name="repro_parto_ativo_cob_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="parto",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantidade_bezerros__gte", 0)),
                name="repro_parto_qtd_nao_negativa",
            ),
        ),
        migrations.AddConstraint(
            model_name="nascimento",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("peso_ao_nascer_kg__isnull", True),
                    ("peso_ao_nascer_kg__gt", 0),
                    _connector="OR",
                ),
                name="repro_nascimento_peso_pos",
            ),
        ),
        migrations.AddIndex(
            model_name="historicoparto",
            index=models.Index(
                fields=["parto", "-criado_em"], name="repro_hist_parto_data_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="perdagestacional",
            index=models.Index(
                fields=["vaca", "-data"], name="repro_perda_vaca_data_idx"
            ),
        ),
    ]
