# Generated by Django 5.2.16 on 2026-07-23 01:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rebanho", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ordenha",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("ativo_registro", models.BooleanField(db_index=True, default=True)),
                ("cancelado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="data"
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        choices=[
                            ("MANHA", "Manhã"),
                            ("TARDE", "Tarde"),
                            ("NOITE", "Noite"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=10,
                        verbose_name="período",
                    ),
                ),
                (
                    "horario",
                    models.TimeField(blank=True, null=True, verbose_name="horário"),
                ),
                (
                    "modo",
                    models.CharField(
                        choices=[
                            ("TOTAL", "Somente total"),
                            ("INDIVIDUAL", "Por vaca"),
                        ],
                        default="TOTAL",
                        max_length=12,
                        verbose_name="modo de registro",
                    ),
                ),
                (
                    "quantidade_total",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="quantidade total (L)",
                    ),
                ),
                (
                    "quantidade_vacas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="quantidade de vacas"
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="responsável"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("REGISTRADA", "Registrada"),
                            ("CORRIGIDA", "Corrigida"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="REGISTRADA",
                        max_length=12,
                        verbose_name="situação",
                    ),
                ),
                (
                    "duplicidade_confirmada",
                    models.BooleanField(
                        default=False,
                        help_text="Registra que outra ordenha no mesmo período foi conscientemente mantida.",
                        verbose_name="duplicidade de período confirmada",
                    ),
                ),
                (
                    "justificativa_divergencia",
                    models.TextField(
                        blank=True, verbose_name="justificativa da divergência"
                    ),
                ),
                (
                    "motivo_correcao",
                    models.TextField(blank=True, verbose_name="motivo da correção"),
                ),
                (
                    "motivo_cancelamento",
                    models.TextField(blank=True, verbose_name="motivo do cancelamento"),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenhas",
                        to="rebanho.lote",
                        verbose_name="lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "ordenha",
                "verbose_name_plural": "ordenhas",
                "ordering": ("-data", "periodo", "horario"),
            },
        ),
        migrations.CreateModel(
            name="DestinoLeite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="data"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("LATICINIO", "Laticínio"),
                            ("CONSUMO", "Consumo próprio"),
                            ("BEZERROS", "Bezerros"),
                            ("QUEIJO", "Queijo"),
                            ("DERIVADOS", "Outros derivados"),
                            ("ARMAZENAMENTO", "Armazenamento"),
                            ("DESCARTE", "Descarte"),
                            ("PERDA", "Perda"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=16,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "quantidade_litros",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="quantidade (L)",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "ordenha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="destinos",
                        to="leite.ordenha",
                        verbose_name="ordenha",
                    ),
                ),
            ],
            options={
                "verbose_name": "destino do leite",
                "verbose_name_plural": "destinos do leite",
                "ordering": ("-data", "tipo"),
            },
        ),
        migrations.CreateModel(
            name="ProducaoAnimal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "quantidade_litros",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="quantidade (L)",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "ordenha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="producoes",
                        to="leite.ordenha",
                        verbose_name="ordenha",
                    ),
                ),
                (
                    "vaca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="producoes_leite",
                        to="rebanho.animal",
                        verbose_name="vaca",
                    ),
                ),
            ],
            options={
                "verbose_name": "produção individual",
                "verbose_name_plural": "produções individuais",
                "ordering": ("ordenha__data", "vaca__identificacao"),
            },
        ),
        migrations.AddIndex(
            model_name="ordenha",
            index=models.Index(
                fields=["data", "periodo"], name="leite_ord_data_periodo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordenha",
            index=models.Index(
                fields=["situacao", "data"], name="leite_ord_situacao_data_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ordenha",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantidade_total__gte", 0)),
                name="leite_ordenha_quantidade_nao_negativa",
            ),
        ),
        migrations.AddIndex(
            model_name="destinoleite",
            index=models.Index(
                fields=["data", "tipo"], name="leite_dest_data_tipo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="destinoleite",
            index=models.Index(fields=["ordenha"], name="leite_dest_ordenha_idx"),
        ),
        migrations.AddConstraint(
            model_name="destinoleite",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantidade_litros__gte", 0)),
                name="leite_destino_quantidade_nao_negativa",
            ),
        ),
        migrations.AddIndex(
            model_name="producaoanimal",
            index=models.Index(
                fields=["vaca", "ordenha"], name="leite_prod_vaca_ord_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="producaoanimal",
            constraint=models.UniqueConstraint(
                fields=("ordenha", "vaca"), name="leite_producao_ordenha_vaca_unica"
            ),
        ),
        migrations.AddConstraint(
            model_name="producaoanimal",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantidade_litros__gte", 0)),
                name="leite_producao_quantidade_nao_negativa",
            ),
        ),
    ]
