# Generated by Django 5.2.16 on 2026-07-23 01:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rebanho", "0001_initial"),
        ("reproducao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lactacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(verbose_name="ordem da lactação"),
                ),
                ("data_inicio", models.DateField(verbose_name="data de início")),
                (
                    "data_encerramento",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de encerramento"
                    ),
                ),
                (
                    "data_secagem",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de secagem"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("ATIVA", "Ativa"),
                            ("SECA", "Seca"),
                            ("ENCERRADA", "Encerrada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ATIVA",
                        max_length=20,
                        verbose_name="situação",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "motivo_cancelamento",
                    models.TextField(blank=True, verbose_name="motivo do cancelamento"),
                ),
                (
                    "parto",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lactacao",
                        to="reproducao.parto",
                    ),
                ),
                (
                    "vaca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lactacoes",
                        to="rebanho.animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "lactação",
                "verbose_name_plural": "lactações",
                "ordering": ("-data_inicio", "-criado_em"),
                "indexes": [
                    models.Index(
                        fields=["vaca", "situacao", "-data_inicio"],
                        name="lact_lact_vaca_sit_data_idx",
                    ),
                    models.Index(
                        fields=["situacao", "data_inicio"],
                        name="lact_lact_sit_inicio_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("situacao", "ATIVA")),
                        fields=("vaca",),
                        name="lact_lact_ativa_vaca_unica",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("situacao", "CANCELADA"), _negated=True),
                        fields=("vaca", "ordem"),
                        name="lact_lact_ordem_vaca_unica",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ordem__gte", 1)),
                        name="lact_lact_ordem_positiva",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("data_encerramento__isnull", True),
                            ("data_encerramento__gte", models.F("data_inicio")),
                            _connector="OR",
                        ),
                        name="lact_lact_fim_apos_inicio",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("data_secagem__isnull", True),
                            ("data_secagem__gte", models.F("data_inicio")),
                            _connector="OR",
                        ),
                        name="lact_lact_secagem_apos_inicio",
                    ),
                ],
            },
        ),
    ]
