# Generated by Django 5.2.16 on 2026-07-23 01:00

import apps.rebanho.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "lote/pasto",
                "verbose_name_plural": "lotes/pastos",
                "ordering": ("nome",),
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("nome"),
                        name="rebanho_lote_nome_ci_unico",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Raca",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("nome", models.CharField(max_length=100, verbose_name="nome")),
                ("descricao", models.TextField(blank=True, verbose_name="descrição")),
                ("ativa", models.BooleanField(default=True, verbose_name="ativa")),
            ],
            options={
                "verbose_name": "raça",
                "verbose_name_plural": "raças",
                "ordering": ("nome",),
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("nome"),
                        name="rebanho_raca_nome_ci_unico",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "identificacao",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="identificação/brinco",
                    ),
                ),
                (
                    "identificacao_provisoria",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="identificação provisória",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nome ou apelido"
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Macho"), ("F", "Fêmea")],
                        max_length=1,
                        verbose_name="sexo",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="data de nascimento"),
                ),
                (
                    "data_nascimento_aproximada",
                    models.BooleanField(
                        default=False, verbose_name="data de nascimento aproximada"
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("NASCIDO_SITIO", "Nascido no sítio"),
                            ("COMPRADO", "Comprado"),
                            ("RECEBIDO", "Recebido"),
                            ("OUTRO", "Outro"),
                        ],
                        default="NASCIDO_SITIO",
                        max_length=20,
                        verbose_name="origem",
                    ),
                ),
                (
                    "data_entrada",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de entrada"
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("ATIVO", "Ativo"),
                            ("VENDIDO", "Vendido"),
                            ("MORTO", "Morto"),
                            ("DESCARTADO", "Descartado"),
                            ("DESAPARECIDO", "Desaparecido"),
                        ],
                        default="ATIVO",
                        max_length=20,
                        verbose_name="situação",
                    ),
                ),
                (
                    "data_saida",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de saída"
                    ),
                ),
                (
                    "motivo_saida",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="motivo da saída"
                    ),
                ),
                (
                    "peso_atual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="peso atual (kg)",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.rebanho.models.foto_animal_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("jpg", "jpeg", "png")
                            )
                        ],
                        verbose_name="foto",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "mae",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filhos_como_mae",
                        to="rebanho.animal",
                        verbose_name="mãe",
                    ),
                ),
                (
                    "pai",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filhos_como_pai",
                        to="rebanho.animal",
                        verbose_name="pai",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animais",
                        to="rebanho.lote",
                        verbose_name="lote atual",
                    ),
                ),
                (
                    "raca",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animais",
                        to="rebanho.raca",
                        verbose_name="raça",
                    ),
                ),
            ],
            options={
                "verbose_name": "animal",
                "verbose_name_plural": "animais",
                "ordering": ("identificacao", "identificacao_provisoria", "nome"),
            },
        ),
        migrations.CreateModel(
            name="HistoricoParentesco",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("justificativa", models.TextField(verbose_name="justificativa")),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_parentesco",
                        to="rebanho.animal",
                    ),
                ),
                (
                    "mae_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historicos_como_mae_anterior",
                        to="rebanho.animal",
                    ),
                ),
                (
                    "mae_nova",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historicos_como_mae_nova",
                        to="rebanho.animal",
                    ),
                ),
                (
                    "pai_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historicos_como_pai_anterior",
                        to="rebanho.animal",
                    ),
                ),
                (
                    "pai_novo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historicos_como_pai_novo",
                        to="rebanho.animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "histórico de parentesco",
                "verbose_name_plural": "históricos de parentesco",
                "ordering": ("-criado_em",),
                "indexes": [
                    models.Index(
                        fields=["animal", "-criado_em"],
                        name="rebanho_hist_parent_animal_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MovimentacaoLote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="data"
                    ),
                ),
                ("motivo", models.CharField(max_length=255, verbose_name="motivo")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes_lote",
                        to="rebanho.animal",
                    ),
                ),
                (
                    "lote_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes_saida",
                        to="rebanho.lote",
                    ),
                ),
                (
                    "novo_lote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes_entrada",
                        to="rebanho.lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimentação de lote",
                "verbose_name_plural": "movimentações de lote",
                "ordering": ("-data", "-criado_em"),
                "indexes": [
                    models.Index(
                        fields=["animal", "-data"], name="rebanho_mov_animal_data_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("lote_anterior__isnull", True),
                            ("novo_lote__isnull", True),
                            models.Q(
                                ("lote_anterior", models.F("novo_lote")), _negated=True
                            ),
                            _connector="OR",
                        ),
                        name="rebanho_mov_lotes_diferentes",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Pesagem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "data",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="data"
                    ),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="peso (kg)",
                    ),
                ),
                (
                    "responsavel",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="responsável"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="observações"),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pesagens",
                        to="rebanho.animal",
                    ),
                ),
            ],
            options={
                "verbose_name": "pesagem",
                "verbose_name_plural": "pesagens",
                "ordering": ("-data", "-criado_em"),
                "indexes": [
                    models.Index(
                        fields=["animal", "-data"], name="rebanho_pes_animal_data_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("peso_kg__gt", 0)),
                        name="rebanho_pesagem_peso_positivo",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(
                fields=["situacao", "sexo"], name="rebanho_animal_sit_sexo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(
                fields=["data_nascimento"], name="rebanho_animal_nasc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(
                fields=["lote", "situacao"], name="rebanho_animal_lote_sit_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(fields=["nome"], name="rebanho_animal_nome_idx"),
        ),
        migrations.AddConstraint(
            model_name="animal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("identificacao__isnull", False),
                        models.Q(("identificacao", ""), _negated=True),
                    ),
                    models.Q(
                        ("identificacao_provisoria__isnull", False),
                        models.Q(("identificacao_provisoria", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="rebanho_animal_tem_identificacao",
            ),
        ),
        migrations.AddConstraint(
            model_name="animal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("peso_atual__isnull", True), ("peso_atual__gt", 0), _connector="OR"
                ),
                name="rebanho_animal_peso_positivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="animal",
            constraint=models.CheckConstraint(
                condition=models.Q(("mae", models.F("id")), _negated=True),
                name="rebanho_animal_mae_nao_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="animal",
            constraint=models.CheckConstraint(
                condition=models.Q(("pai", models.F("id")), _negated=True),
                name="rebanho_animal_pai_nao_self",
            ),
        ),
    ]
