# Generated by Django 5.2.16 on 2026-07-23 01:36

import apps.core.validators
import apps.rebanho.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rebanho", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.rebanho.models.foto_animal_upload_to,
                validators=[apps.core.validators.validar_upload_imagem],
                verbose_name="foto",
            ),
        ),
    ]
