# Generated by Django 5.2.16 on 2026-07-23 01:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("data_hora", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "cf_connecting_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("x_forwarded_for", models.CharField(blank=True, max_length=255)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("modulo", models.CharField(db_index=True, max_length=80)),
                ("entidade", models.CharField(db_index=True, max_length=120)),
                ("identificador", models.CharField(db_index=True, max_length=80)),
                ("operacao", models.CharField(db_index=True, max_length=40)),
                ("dados_anteriores", models.JSONField(blank=True, default=dict)),
                ("dados_novos", models.JSONField(blank=True, default=dict)),
                ("justificativa", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoria",
                "verbose_name_plural": "registros de auditoria",
                "ordering": ["-data_hora"],
                "indexes": [
                    models.Index(
                        fields=["modulo", "entidade", "identificador"],
                        name="auditoria_r_modulo_48d786_idx",
                    )
                ],
            },
        ),
    ]
